### ISSUE TITLE
Pink kanali ne rade

### ISSUE THREAD

**Issue by omerdan** [segvic/plugin.video.mojawebtv#1]
postavljeni server za pink kanale je netacan ili ugasen.
server[2]=... .57.183

google aplikacija se redovno update-uje vidim i radi u njoj pink, a KODI zapostavljate?
android je za luzere, popravite opensource kodi PLEASE.

PS. duboki respect za programere moje webtv, prva savremeno zamisljena i odradjena stvar u bht-u. svaka cast.

**Comment by segvic** [comment]
Ide update brzo, samo ne stizemo, nije zaboravljeno

**Comment by segvic** [comment]
Update je live - uskoro ce svi kanali biti na novoj streaming platformi.
